version: '3'
services:
  node-red:
    build: ./node-red
    volumes:
      - './node-red/data:/data'
    ports:
      - '1880:1880'
    restart: on-failure

  # AMQP Broker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=qu4lity
      - RABBITMQ_DEFAULT_PASS=qu4lity
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    volumes:
      - './mongo/entrypoint:/docker-entrypoint-initdb.d/'
      - './mongo/data:/data/db'
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: qu4lity
        MONGO_INITDB_ROOT_PASSWORD: qu4lity
        MONGO_INITDB_DATABASE: qu4lity

  mongo-express:
    image: mongo-express
    restart: always
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: qu4lity
        ME_CONFIG_MONGODB_ADMINPASSWORD: qu4lity
